language: julia
os:
  - linux
julia:
  - 1.1
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
  - julia: nightly
coverage: true
addons:
  apt:
    packages:
    - gfortran
install:
  pip install --user mkdocs-cinder
