language: julia
os:
  - linux
julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
matrix:
  allow_failures:
  - julia: nightly
addons:
  apt:
    packages:
    - gfortran
install:
  pip install --user mkdocs-cinder
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - |
      if [[ "$TRAVIS_JULIA_VERSION" == "0.6" ]]; then
        julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("LadeGCM"); Pkg.test("LadeGCM"; coverage=true)'
      else
        julia -e 'using Pkg; Pkg.test("LadeGCM"; coverage=true)'
      fi
after_success:
    # Upload docs
  - |
      if [[ "$TRAVIS_JULIA_VERSION" == "0.6"  && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" ]]; then
        julia -e 'Pkg.add("Documenter")'
        julia -e 'cd(Pkg.dir("LadeGCM")); include(joinpath("docs", "make.jl"))'
      fi
  # Coverage report
  - |
      if [[ "$TRAVIS_JULIA_VERSION" == "0.6" ]]; then
        julia -e 'cd(Pkg.dir("LadeGCM")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
      fi
