site_name:        LadeGCM.jl
repo_url:         https://github.com/Libbum/LadeGCM.jl
site_description: Steve Lade's stylised global climate–carbon cycle model.
site_author:      Tim DuBois

theme: cinder

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - https://cdn.plot.ly/plotly-latest.min.js
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - API: api.md
